### ISSUE TITLE
cert-manager.io/* annotations are not allowed

### ISSUE THREAD

**Issue by hans-fischer** [maelvls/secret-transform#11]
While using the newest cert-manager i deployed the following object:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: intermediate-ca
  namespace: database-operators
spec:
  secretName: database-ca
  secretTemplate:
    annotations:
      cert-manager.io/allow-direct-injection: "true"
      cert-manager.io/secret-copy-tls.crt: "ca.crt"
      cert-manager.io/secret-copy-tls.key: "ca.key"
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
  commonName: "k8s-main-dbs CA"
  isCA: true
  subject:
    organizations:
      - "Database"
  privateKey:
    algorithm: RSA
    size: 4096
  usages:
    - cert sign
    - crl sign
```

the following error occures:
```
error when patching "/Users/hfi/tmp/intermediate-ca.yml": admission webhook "webhook.cert-manager.io" denied the request: [spec.secretTemplate.annotations: Invalid value: "cert-manager.io/secret-copy-tls.crt": cert-manager.io/* annotations are not allowed, spec.secretTemplate.annotations: Invalid value: "cert-manager.io/secret-copy-tls.key": cert-manager.io/* annotations are not allowed]
```

Why using the namespace of cert-manager? Why dont you use your own namespace for the annotions?
Why cert-manager.io/secret-copy-tls.crt ? Why not maelvls.secret-transform/secret-copy-tls.crt ?

In the mean time.. a kyverno-policy to patial replace your operator. 

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: copy-tls-to-ca
spec:
  rules:
    - name: copy-tls-data-to-ca
      match:
        resources:
          kinds:
            - Secret
          selector:
            matchLabels:
              cp/copy-tls-to-ca: ""
      mutate:
        patchStrategicMerge:
          data:
            ca.crt: '{{ request.object.data."tls.crt" }}'
            ca.key: '{{ request.object.data."tls.key" }}'
```

Thank you for your time you put into this project. ❤️
Best
Hans
